---
server:
  tomcat:
    max-threads: 128
    uri-encoding: UTF-8
  gateway:
    name: gateway

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      override-none: true
  zipkin:
#    base-url: http://localhost:7008
#    rabbitmq:
#      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.1
  rabbitmq:
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:123456}
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:192.168.1.200}
    virtualHost: ${RABBITMQ_VHOST:dy}
  redis:
      cluster:
        nodes: ${REDIS_NODES:192.168.1.211:6479,192.168.1.211:6579,192.168.1.211:6679,192.168.1.212:6779,192.168.1.212:6879,192.168.1.212:6979}
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:192.168.1.213}:${DATASOURCE_PORT:3306}/dy-dev?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Wanbit.2013}
    druid:
      maxActive: ${DATASOURCE_DRUID_MAXACTIVE:4}
      initialSize: ${DATASOURCE_DRUID_INITIALSIZE:4}
      minIdle: ${DATASOURCE_DRUID_MINIDLE:4}
      maxWait: ${DATASOURCE_DRUID_MAXWAIT:60000}
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE

---
#mybatis:
#  # Mybatis配置Mapper路径
#  mapper-locations: classpath:mapper/*.xml
##  type-aliases-package: com.witc.common.moduals.xx.entity

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.witc.common.moduals.xx.entity
#  typeEnumsPackage: com.witc.common.moduals.xx.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

pagehelper:
  params: count=countSql
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
  reasonable: 'true'
  support-methods-arguments: 'true'

---
## Discovery Center
eureka:
  instance:
    # 以IP方式注册到注册中心，默认是应用名
    prefer-ip-address: true
    # 与注册中心的周期心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间
    lease-expiration-duration-in-seconds: 30
    # 节点状态和安全检查路径
    metadata-map:
      management:
        context-path: ${server.context-path}
  client:
    # 从注册中心拉取服务列表时间间隔
    registry-fetch-interval-seconds: 5
    # 注册中心地址
    service-url:
      defaultZone: http://witcdy:Wanbit.2013@${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:7000}/discovery/eureka

---
logging:
  level:
    root: INFO
    com.witc: debug

#springboot2.0的时候必须配置include: '*'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

---
api:
  url:
    pre: /api
session:
  checked:
    redirect:
      url: /login
base:
  boot:
    is_need_validate: true

witc:
  core:
    jwt:
      enable: false
  tenant:
    column: company_id
    tables:
      - sys_companyinfo
      - sys_company_lable
