---
server:
  context-path: /biz
  port: 9004
  gateway:
    name: gateway
spring:
  application:
    name: dy-biz

logging:
  level:
    com.witc.biz.dao: debug

mybatis:
  # Mybatis配置Mapper路径
  mapper-locations: classpath:mapper/*.xml
  # Mybatis配置Model类对应
  type-aliases-package: com.witc.common.moduals.biz.entity